### ISSUE TITLE
Need not to make it appear gradually

### ISSUE THREAD

**Issue by ooker777** [michaelpri10/SE-References#2]
it's just unnecessary for me. When I need to cite a source, I already have the link in clipboard. I want to paste it fast.

**Comment by michaelpri10** [comment]
@ooker777 I'm not really sure what you're saying. What do you mean it appears gradually?

**Comment by ooker777** [comment]
Yes. I think it would be more productive if it appears and disappears immediately. 

Ooker.

**Comment by michaelpri10** [comment]
@ooker777 Are you talking about the box in which you post your links and the title of the reference?

**Comment by ooker777** [comment]
Yes. Can you see the box is shading?
![screenshot 12](https://cloud.githubusercontent.com/assets/6695517/9149079/f23ebf34-3dc0-11e5-9e37-b80369222d93.png)
![screenshot 13](https://cloud.githubusercontent.com/assets/6695517/9149080/f24d87a8-3dc0-11e5-935c-182f4a81d0cb.png)
